// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RimettimiInSesto.Api.Data;

#nullable disable

namespace RimettimiInSesto.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913172135_AggiungeTipoPrestazioneEOreContratto")]
    partial class AggiungeTipoPrestazioneEOreContratto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AcquistoPacchetto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataAcquisto")
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Prezzo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RicettaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Scadenza")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeduteResidue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeduteTotali")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.HasIndex("RicettaId")
                        .IsUnique();

                    b.ToTable("AcquistiPacchetto");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Appuntamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcquistoPacchettoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataMinuti")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FisioterapistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModificaRichiestaDataOra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModificaRichiestaIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoAnnullamento")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("NotificaGiaDataAltrove")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Percorso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RicettaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcquistoPacchettoId");

                    b.HasIndex("FisioterapistaId");

                    b.HasIndex("PazienteId");

                    b.HasIndex("RicettaId");

                    b.ToTable("Appuntamenti");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AssenzaFisioterapista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<int>("FisioterapistaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatoApprovazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapistaId");

                    b.ToTable("AssenzeFisioterapisti");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AuditLogAccessoClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppuntamentoGiustificativoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoAccesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.HasIndex("UtenteId");

                    b.ToTable("AuditLogAccessiClinici");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.CartellaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnamnesiPatologicaRemota")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataFineTerapia")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataInizioTerapia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EsameObiettivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("EsamiSpecialistici")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaFisioterapista")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaMedicoResponsabile")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicazioniPaziente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteSostituzione")
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgrammaRiabilitativo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenienza")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VasFinale")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VasIniziale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.ToTable("CartelleCliniche");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.ChiusuraStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChiusureStudio");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Consenso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firmatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersioneInformativa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.ToTable("Consensi");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Controindicazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllergiaFans")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisturbiCardiocircolatori")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Epilessia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GraveOsteoporosi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gravidanza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterventiChirurgici")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LesioniCutaneeOFratture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MezziDiSintesiOProtesi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeoplasiaInAttoOPregressa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pacemaker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProtesiAcustiche")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StatoInfiammatorioAcuto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TendenzaEmorragie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerapieFarmacologicheInAtto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId")
                        .IsUnique();

                    b.ToTable("Controindicazioni");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Fisioterapista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoProfiloUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OreSettimanaliContratto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternDisponibilita")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId")
                        .IsUnique();

                    b.ToTable("Fisioterapisti");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.ImpostazioniAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinestraPrenotazioneMassimaGiorni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreavvisoMinimoCancellazioneOre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SogliaAvvisoDisponibilitaAnticipataGiorni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SogliaPriorizzazioneRicettaInIntegrazioneGiorni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValiditaPropostaSlotOre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniAgenda");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.ImpostazioniListino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurataValiditaPacchettoMesi")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("MattinaFine")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("MattinaInizio")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrariApertura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("PomeriggioFine")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("PomeriggioInizio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoPacchettoPrivato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoSedutaSingolaManuale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuotaTicketRegionale")
                        .HasColumnType("TEXT");

                    b.Property<int>("SedutePacchettoPrivato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniListino");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.NotaOperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.ToTable("NoteOperative");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.NotaSeduta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppuntamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrataIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppuntamentoId")
                        .IsUnique();

                    b.ToTable("NoteSeduta");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Notifica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppuntamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreataIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppuntamentoId");

                    b.HasIndex("PazienteId");

                    b.ToTable("Notifiche");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcquistoPacchettoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppuntamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataIncasso")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiferimentoStripe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPrestazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcquistoPacchettoId");

                    b.HasIndex("AppuntamentoId");

                    b.HasIndex("PazienteId");

                    b.ToTable("Pagamenti");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Paziente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique()
                        .HasFilter("[CodiceFiscale] IS NOT NULL");

                    b.ToTable("Pazienti");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.PropostaSlotAlternativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppuntamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Esito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Scadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotProposti")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SlotScelto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppuntamentoId");

                    b.ToTable("ProposteSlotAlternativo");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Ricetta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppuntoSegreteria")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceEsenzione")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodicePrestazioneBranca")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrettiCorporei")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Esenzione")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FinestraCompletamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImportoTicket")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntegrazioneRichiestaIl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicoPrescrittore")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroONre")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroSeduteProscritte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuesitoDiagnostico")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Scadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.ToTable("Ricette");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Ricevuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImpostaBolloApplicata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InviataSistemaTs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroProgressivo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OpposizioneSistemaTs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stornata")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.HasIndex("Anno", "NumeroProgressivo")
                        .IsUnique();

                    b.ToTable("Ricevute");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.UtentePaziente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.HasIndex("UtenteId", "PazienteId")
                        .IsUnique();

                    b.ToTable("UtentiPazienti");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AcquistoPacchetto", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("Pacchetti")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RimettimiInSesto.Api.Models.Ricetta", "Ricetta")
                        .WithOne("CicloGenerato")
                        .HasForeignKey("RimettimiInSesto.Api.Models.AcquistoPacchetto", "RicettaId");

                    b.Navigation("Paziente");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Appuntamento", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.AcquistoPacchetto", "AcquistoPacchetto")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("AcquistoPacchettoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RimettimiInSesto.Api.Models.Fisioterapista", "Fisioterapista")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("FisioterapistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RimettimiInSesto.Api.Models.Ricetta", "Ricetta")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcquistoPacchetto");

                    b.Navigation("Fisioterapista");

                    b.Navigation("Paziente");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AssenzaFisioterapista", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Fisioterapista", "Fisioterapista")
                        .WithMany("Assenze")
                        .HasForeignKey("FisioterapistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fisioterapista");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AuditLogAccessoClinico", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany()
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.CartellaClinica", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("Cicli")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Consenso", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("Consensi")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Controindicazioni", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithOne("Controindicazioni")
                        .HasForeignKey("RimettimiInSesto.Api.Models.Controindicazioni", "PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Fisioterapista", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", "Utente")
                        .WithOne("ProfiloFisioterapista")
                        .HasForeignKey("RimettimiInSesto.Api.Models.Fisioterapista", "UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.NotaOperativa", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("NoteOperative")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.NotaSeduta", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Appuntamento", "Appuntamento")
                        .WithOne("RiepilogoSeduta")
                        .HasForeignKey("RimettimiInSesto.Api.Models.NotaSeduta", "AppuntamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appuntamento");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Notifica", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Appuntamento", "Appuntamento")
                        .WithMany()
                        .HasForeignKey("AppuntamentoId");

                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany()
                        .HasForeignKey("PazienteId");

                    b.Navigation("Appuntamento");

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Pagamento", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.AcquistoPacchetto", "AcquistoPacchetto")
                        .WithMany("Pagamenti")
                        .HasForeignKey("AcquistoPacchettoId");

                    b.HasOne("RimettimiInSesto.Api.Models.Appuntamento", "Appuntamento")
                        .WithMany()
                        .HasForeignKey("AppuntamentoId");

                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany()
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcquistoPacchetto");

                    b.Navigation("Appuntamento");

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.PropostaSlotAlternativo", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Appuntamento", "Appuntamento")
                        .WithMany("ProposteSlot")
                        .HasForeignKey("AppuntamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appuntamento");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Ricetta", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("Ricette")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Ricevuta", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.UtentePaziente", b =>
                {
                    b.HasOne("RimettimiInSesto.Api.Models.Paziente", "Paziente")
                        .WithMany("UtentiCollegati")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RimettimiInSesto.Api.Models.ApplicationUser", "Utente")
                        .WithMany("PazientiCollegati")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.AcquistoPacchetto", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("Pagamenti");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.ApplicationUser", b =>
                {
                    b.Navigation("PazientiCollegati");

                    b.Navigation("ProfiloFisioterapista");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Appuntamento", b =>
                {
                    b.Navigation("ProposteSlot");

                    b.Navigation("RiepilogoSeduta");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Fisioterapista", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("Assenze");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Paziente", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("Cicli");

                    b.Navigation("Consensi");

                    b.Navigation("Controindicazioni");

                    b.Navigation("NoteOperative");

                    b.Navigation("Pacchetti");

                    b.Navigation("Ricette");

                    b.Navigation("UtentiCollegati");
                });

            modelBuilder.Entity("RimettimiInSesto.Api.Models.Ricetta", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("CicloGenerato");
                });
#pragma warning restore 612, 618
        }
    }
}
